policies:
  - name: Update Updatecli policies
    policy: ghcr.io/updatecli/policies/updatecli/autodiscovery:0.8.1@sha256:f8edda1a6cbf0d7274e2b847ede29fc4dc70dd5302ccb8575ae21b069cc0d8a0
    values:
      - updatecli/values.d/scm.yaml

  - name: Update Helm charts
    policy: ghcr.io/updatecli/policies/autodiscovery/helm:0.9.1@sha256:b53ead17fa1cd26d1147c0f49d53b273b2cd7df234c514d531a6ab993e37a58b
    values:
      - updatecli/values.d/scm.yaml

  - name: Update Helm charts
    policy: ghcr.io/updatecli/policies/autodiscovery/helmfile:0.7.0@sha256:b913d8bd7b2470e0873cf6e5ae5ba5826ea7c7c27c106c450d60061ee14cf193
    values:
      - updatecli/values.d/scm.yaml

  - name: Update githubactions
    policy: ghcr.io/updatecli/policies/autodiscovery/githubaction:0.3.0@sha256:3b5425da2a2a2b89bb69463f1294704c33730358c66140efb93cab14b2868b06
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/githubaction.yaml
