ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: app.updatecli.io
  tls:
    - secretName: udash-tls
      hosts:
        - app.updatecli.io

