repositories:
  - name: cert-manager
    url: https://charts.jetstack.io
helmDefaults:
  createNamespace: true
  timeout: 180
  atomic: true
  verify: false
  wait: true
releases:
  - name: cert-manager
    namespace: cert-manager
    version: v1.12.3
    chart: cert-manager/cert-manager
    disableValidationOnInstall: true
    wait: true
    waitForJobs: true
    values:
      - installCRDs: true
