repositories:
  - name: bitnami
    url: registry-1.docker.io/bitnamicharts
    oci: true
  - name: updatecli
    url: https://updatecli.github.io/charts
releases:
  - name: postgresql
    namespace: udash
    chart: bitnami/postgresql
    version: 12.6.5
    secrets:
      - ../secrets.d/udash/postgresql.yaml
    wait: true
  - name: udash
    namespace: udash
    chart: updatecli/udash
    version: 0.2.0
    values:
      - ../values.d/udash/ingress.yaml
    secrets:
      - ../secrets.d/udash/udash.yaml
    wait: true

