repositories:
  - name: bitnami
    url: registry-1.docker.io/bitnamicharts
    oci: true
  - name: updatecli
    url: https://updatecli.github.io/charts
releases:
  - name: postgresql
    namespace: udash
    chart: bitnami/postgresql
    version: 12.6.5
    secrets:
      - ../secrets.d/udash/postgresql.yaml
    wait: true
  - name: udash
    namespace: udash
    #chart: updatecli/udash
    chart: /home/olblak/Projects/Updatecli/charts/charts/udash
    # version: 0.1.1
    values:
      - ../values.d/udash/ingress.yaml
    secrets:
      - ../secrets.d/udash/udash.yaml
    wait: true

