repositories:
  - name: bitnami
    url: registry-1.docker.io/bitnamicharts
    oci: true
  - name: updatecli
    url: https://updatecli.github.io/charts
releases:
  - name: postgresql
    namespace: udash
    chart: bitnami/postgresql
    version: 16.2.3
    secrets:
      - ../secrets.d/udash/postgresql.yaml
    wait: true
  - name: udash
    namespace: udash
    chart: updatecli/udash
    version: 0.10.0
    values:
      - ../values.d/udash/ingress.yaml
    secrets:
      - ../secrets.d/udash/udash.yaml
    wait: true

  - name: udash-agent
    namespace: udash
    chart: updatecli/udash-agent
    version: 0.3.0
    values:
      - ../values.d/udash/agent.yaml
    secrets:
      - ../secrets.d/udash/udash.yaml
      - ../secrets.d/udash/agent.yaml
    wait: true
