repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: updatecli
    url: ghcr.io/updatecli/charts
    oci: true
releases:
  - name: updatemonitor
    namespace: updatemonitor
    chart: updatecli/updatemonitor
    version: 0.2.0
    values:
      - ../values.d/updatemonitor.yaml
    secrets:
      - ../secrets.d/updatemonitor.yaml
    wait: true

